### ISSUE TITLE
when try run the code i coudn't find the mentioned dataset "merged_dataset_weighted.csv" is there any way to obtain the exact dataset by comibaining the given data sets ,when i try to combile the codes package check_X error also showing i am attaching the error along with this pfa

### ISSUE THREAD

**Issue by sakhilsakhil** [alireza-mht/GreyWolfOptimization-MKSVM#2]
![dataset error](https://user-images.githubusercontent.com/61202192/107605160-5d1c7500-6c58-11eb-9a40-60f7c0ce24f5.PNG)
![code error](https://user-images.githubusercontent.com/61202192/107605350-f186d780-6c58-11eb-9a0c-ae19a585c6ba.PNG)

**Comment by alireza-mht** [comment]
The dataset in the repository is not the original one. You can test this project with any other dataset, but you need to configure it (Changing names). I will check the error and get back to you soon.

**Comment by alireza-mht** [comment]
Here is the link to the bytecode dataset:
https://github.com/CyberScienceLab/Datasets/blob/master/IoT/OpCode/OpCode/bytecode.7z

**Comment by alireza-mht** [comment]
I have added the validation.py. It should work now.
