### ISSUE TITLE
When try to load the data set it shows the error "Cannot take a larger sample than population when 'replace=False'"

### ISSUE THREAD

**Issue by sakhilsakhil** [alireza-mht/GreyWolfOptimization-MKSVM#3]
When try to load the data set it shows the error "Cannot take a larger sample than population when 'replace=False'" 
here i am attaching the screenshot of that error
![error](https://user-images.githubusercontent.com/61202192/114172563-6faee400-9953-11eb-9561-48c964953cb3.png)

**Comment by sakhilsakhil** [comment]
you have mentioned that we have to set parameters in  param method and set the numbers of your features in your dataset(in optimizer.py)how can i set the parameters given by the dataset(Here is the link to dataset: https://github.com/CyberScienceLab/Datasets/blob/master/IoT/OpCode/OpCode/bytecode.7z) .I converted  from the txt format to csv format

**Comment by alireza-mht** [comment]
In optimizer.py, we have a param method. In the code, the number of features is set to 24. So you should change it according to the number of features in your dataset. The number of features is equal to the number of columns in the dataset.
In the attached screenshot in line 17, you only choose the first 10000000 samples of your dataset for processing. So you should decrease the value in line 17 based on the number of rows in the dataset. Since the dataset is huge, you can start with the lower samples.

**Comment by sakhilsakhil** [comment]
the given data set is in txt format how can i convert it into the csv format with the required format
![newerror](https://user-images.githubusercontent.com/61202192/114301491-cd256b00-9ae2-11eb-84a8-441d251543eb.jpg)

**Comment by alireza-mht** [comment]
You can do it by using the Panda library.
Check out this page:
https://datatofish.com/convert-text-file-to-csv-using-python-tool-included/

**Comment by sakhilsakhil** [comment]
I try to convert the txt file using the above code but when i try to open the csv file in excel .
![cv error](https://user-images.githubusercontent.com/61202192/114315138-1d202400-9b1b-11eb-9664-ea63d4035772.png)
when try to train (load )that data set  the  #3 is occuring

**Comment by sakhilsakhil** [comment]
when i adjust the feature count to 24 (number columns) the data set start to preprocess but key error is occurring to 
'SystemStatus(SystemClass)' here  i am  attaching the screen short of the error
![2021-04-12](https://user-images.githubusercontent.com/61202192/114409558-30d59400-9bc8-11eb-87d5-0414df855c3d.png)
![2021-04-12 (2)](https://user-images.githubusercontent.com/61202192/114409630-43e86400-9bc8-11eb-963d-884054be21eb.png)

**Comment by alireza-mht** [comment]
In line 36, we split the label column which is a column with the name of SystemStatus(SystemClass). I think the columns in your dataset do not have names.

**Comment by sakhilsakhil** [comment]
i am using the dataset provided in the link( https://github.com/CyberScienceLab/Datasets/blob/master/IoT/OpCode/OpCode/bytecode.7z) that dataset dosnot condain any label cloumn .

**Comment by sakhilsakhil** [comment]
sir there is no label column in the data set .I am using the dataset
provided by the link in the repository,if there is any another data set
with label column

**Comment by alireza-mht** [comment]
Most of the time, the last column is the label column. Please check the dataset and if you cannot find the label column, send an email to Hamed for more information about the dataset.

**Comment by hamedhpajouh** [comment]
Regarding your labels, we provided labels in a separate file which you need to load separately and feed the model. I close this issue cause this is a nighter bug nor feature anymore. You can ask your question in Stackoverflow.
